/*
 * Copyright (c) 2025 Rumbledethumps
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* English */

#if !defined(X) && defined(__INTELLISENSE__)
#define X(name, value)
#endif

X(STR_ERR_INVALID_ARGUMENT, "?Invalid argument\n")
X(STR_ERR_ROM_NOT_INSTALLED, "?ROM not installed\n")

X(STR_ON, "On")
X(STR_OFF, "Off")
X(STR_ENABLED, "Enabled")
X(STR_DISABLED, "Disabled")
X(STR_WORLDWIDE, "Worldwide")
X(STR_PARENS_NONE, "(none)")
X(STR_PARENS_SET, "(set)")
