#!/usr/bin/env python3
# Copyright (c) 2026 Rumbledethumps
#
# SPDX-License-Identifier: BSD-3-Clause
#
# The PSG's sine table as a ROM. aud_init computes it at runtime with
# libm — lround(-cos(2*pi*i/256) * 127), phase 0 at the trough — so the
# RTL carries the same 256 bytes as a package, and test_font holds this
# emission byte for byte against the running table.

import argparse
import math


def lround(x):
    return math.floor(x + 0.5) if x >= 0 else math.ceil(x - 0.5)


def table():
    return [lround(math.cos(math.pi * 2.0 / 256 * i) * -127)
            for i in range(256)]


def emit_sv(path):
    t = table()
    with open(path, "w") as f:
        f.write("// Generated by aud_sine_gen.py. Do not edit.\n")
        f.write("package aud_sine_pkg;\n")
        f.write("/* verilator lint_off UNUSEDPARAM */\n")
        f.write("localparam logic [7:0] AUD_SINE[256] = '{\n")
        for i in range(0, 256, 8):
            row = ", ".join(f"8'h{v & 0xFF:02X}" for v in t[i:i + 8])
            f.write(f"    {row}{',' if i < 248 else ''}\n")
        f.write("};\n")
        f.write("/* verilator lint_on UNUSEDPARAM */\n")
        f.write("endpackage\n")


def emit_h(path):
    t = table()
    with open(path, "w") as f:
        f.write("/* Generated by aud_sine_gen.py. Do not edit. */\n")
        f.write("#include <stdint.h>\n")
        f.write("static const int8_t AUD_SINE_TABLE[256] = {\n")
        for i in range(0, 256, 12):
            row = ", ".join(str(v) for v in t[i:i + 12])
            f.write(f"    {row}{',' if i + 12 < 256 else ''}\n")
        f.write("};\n")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-sv")
    ap.add_argument("--emit-h")
    args = ap.parse_args()
    if args.emit_sv:
        emit_sv(args.emit_sv)
    if args.emit_h:
        emit_h(args.emit_h)
