#!/usr/bin/env python3
# Copyright (c) 2026 Rumbledethumps
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generates the vid_font ROM tables from src/vga/term/font.c, replicating
# font_init exactly: font16 is ASCII low half plus the CP437 high half
# (font_set_code_page(437) at boot), font_dec_16 is the DEC Special
# Graphics table built from dec_glyph_map, italic16 is the ASCII italic
# face verbatim. The C arrays are row-major with a 128-byte stride; the
# ROMs are glyph-major, addressed {code, scanrow}, which is how the
# scanout fetches. The parity test compares every byte against the
# tables emu_core builds at runtime, so drift here cannot hide.

import argparse
import re
import sys
from pathlib import Path

FONT_C = Path(__file__).resolve().parents[3] / "src/vga/term/font.c"

DEC_MAP_BLANK = 0xFFFF
DEC_MAP_ASCII = 0x10000


def parse_array(text, name):
    m = re.search(re.escape(name) + r"\[\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        sys.exit(f"vid_font_gen: array {name} not found")
    return [int(t, 0) for t in re.findall(r"0[xX][0-9a-fA-F]+", m.group(1))]


def parse_dec_map(text):
    m = re.search(r"dec_glyph_map\[0x20\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        sys.exit("vid_font_gen: dec_glyph_map not found")
    entries = []
    for line in m.group(1).splitlines():
        line = re.sub(r"/\*.*?\*/", "", line)
        line = re.sub(r"//.*", "", line)
        line = line.strip().rstrip(",")
        if not line:
            continue
        v = 0
        for tok in line.split("|"):
            tok = tok.strip()
            if tok == "DEC_MAP_BLANK":
                v |= DEC_MAP_BLANK
            elif tok == "DEC_MAP_ASCII":
                v |= DEC_MAP_ASCII
            else:
                v |= int(tok.rstrip("u"), 0)
        entries.append(v)
    if len(entries) != 0x20:
        sys.exit(f"vid_font_gen: dec_glyph_map has {len(entries)} entries")
    return entries


def build_tables():
    text = FONT_C.read_text()
    ascii16 = parse_array(text, "FONT16_ASCII")
    cp437_16 = parse_array(text, "FONT16_CP437")
    italic_src = parse_array(text, "FONT16_ASCII_ITALIC")
    ascii8 = parse_array(text, "FONT8_ASCII")
    cp437_8 = parse_array(text, "FONT8_CP437")
    dec_map = parse_dec_map(text)
    for name, arr, want in (("FONT16_ASCII", ascii16, 2048),
                            ("FONT16_CP437", cp437_16, 2048),
                            ("FONT16_ASCII_ITALIC", italic_src, 2048),
                            ("FONT8_ASCII", ascii8, 1024),
                            ("FONT8_CP437", cp437_8, 1024)):
        if len(arr) != want:
            sys.exit(f"vid_font_gen: {name} has {len(arr)} bytes, want {want}")

    # font16, glyph-major: ASCII low half, CP437 high half.
    font16 = [0] * 4096
    for row in range(16):
        for code in range(128):
            font16[code * 16 + row] = ascii16[row * 128 + code]
        for code in range(128, 256):
            font16[code * 16 + row] = cp437_16[row * 128 + (code - 128)]

    # font_dec_16, glyph-major over the 0x5F..0x7E window.
    dec16 = [0] * 512
    for row in range(16):
        for idx in range(0x20):
            m = dec_map[idx]
            if m == DEC_MAP_BLANK:
                continue
            if m & DEC_MAP_ASCII:
                dec16[idx * 16 + row] = ascii16[row * 128 + (m & 0xFF)]
            else:
                dec16[idx * 16 + row] = cp437_16[row * 128 + ((m & 0xFF) - 0x80)]

    # italic16, glyph-major, low half only.
    italic16 = [0] * 2048
    for row in range(16):
        for code in range(128):
            italic16[code * 16 + row] = italic_src[row * 128 + code]

    # font8, same build as font16 at half height, for the mode 1 cells.
    font8 = [0] * 2048
    for row in range(8):
        for code in range(128):
            font8[code * 8 + row] = ascii8[row * 128 + code]
        for code in range(128, 256):
            font8[code * 8 + row] = cp437_8[row * 128 + (code - 128)]

    return font16, dec16, italic16, font8


def sv_array(name, data):
    lines = [f"    localparam logic [7:0] {name} [{len(data)}] = '{{"]
    for i in range(0, len(data), 16):
        row = ", ".join(f"8'h{b:02X}" for b in data[i:i + 16])
        sep = "," if i + 16 < len(data) else ""
        lines.append(f"        {row}{sep}")
    lines.append("    };")
    return "\n".join(lines)


def c_array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


HEADER = """\
/*
 * Copyright (c) 2026 Rumbledethumps
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Generated by vid_font_gen.py from src/vga/term/font.c - do not edit.
 * Glyph-major: byte at [code * 16 + scanrow].
 */
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-sv", metavar="FILE")
    ap.add_argument("--emit-h", metavar="FILE")
    args = ap.parse_args()
    font16, dec16, italic16, font8 = build_tables()
    if args.emit_sv:
        out = [HEADER, "package vid_font_pkg;", "",
               "    /* verilator lint_off UNUSEDPARAM */", "",
               sv_array("VID_FONT16", font16), "",
               sv_array("VID_FONT_DEC16", dec16), "",
               sv_array("VID_ITALIC16", italic16), "",
               sv_array("VID_FONT8", font8), "",
               "    /* verilator lint_on UNUSEDPARAM */", "",
               "endpackage", ""]
        Path(args.emit_sv).write_text("\n".join(out))
    if args.emit_h:
        out = [HEADER,
               "#ifndef _VID_FONT_TABLES_H_", "#define _VID_FONT_TABLES_H_",
               "", "#include <stdint.h>", "",
               c_array("VID_FONT16", font16), "",
               c_array("VID_FONT_DEC16", dec16), "",
               c_array("VID_ITALIC16", italic16), "",
               c_array("VID_FONT8", font8), "",
               "#endif /* _VID_FONT_TABLES_H_ */", ""]
        Path(args.emit_h).write_text("\n".join(out))


if __name__ == "__main__":
    main()
