# The libretro buildbot.
#
.core-defs:
  variables:
    CORENAME: rp6502
    CMAKE_SOURCE_ROOT: src/host/libretro
    GIT_DEPTH: 0
    CORE_ARGS: -DRP6502_STRICT_SUBMODULES=ON -DRP6502_TESTS=OFF -DRP6502_VERSION_FROM_GIT=ON -DRP6502_GIT=$CI_COMMIT_SHORT_SHA

include:
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-msvc19.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-x86.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-arm64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

stages:
  - build-prepare
  - build-shared
  - build-static

# Desktops.
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs

libretro-build-windows-x64:
  extends:
    - .libretro-windows-msvc19-cmake-x86_64
    - .core-defs
  variables:
    EXTRA_PATH: Release

libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86_64
    - .core-defs

libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs

libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs

libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs

libretro-build-linux-aarch64:
  extends:
    - .libretro-linux-cmake-aarch64
    - .core-defs

android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs
