# The Pocket UI prints "Version " itself, so the tagged form is the bare
# tag; Analogue caps the field at 31 characters.
if(VERSION)
    set(_ver "${VERSION}")
elseif(CI)
    set(_ver "CI ${CI}")
else()
    string(TIMESTAMP _ver "%b %d %Y %H:%M:%S %Z")
endif()
string(LENGTH "${_ver}" _len)
if(_len GREATER 31)
    message(FATAL_ERROR "metadata.version over 31 chars: '${_ver}'")
endif()
string(TIMESTAMP _date "%Y-%m-%d" UTC)
file(READ "${CORE_JSON}" _json)
foreach(_key version date_release)
    string(REGEX MATCHALL "\"${_key}\"[ \t]*:" _m "${_json}")
    list(LENGTH _m _n)
    if(NOT _n EQUAL 1)
        message(FATAL_ERROR "${CORE_JSON}: expected one \"${_key}\", found ${_n}")
    endif()
endforeach()
string(REGEX REPLACE "(\"version\"[ \t]*:[ \t]*)\"[^\"]*\"" "\\1\"${_ver}\""
    _json "${_json}")
string(REGEX REPLACE "(\"date_release\"[ \t]*:[ \t]*)\"[^\"]*\"" "\\1\"${_date}\""
    _json "${_json}")
file(WRITE "${CORE_JSON}" "${_json}")
